sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  global:
    # GitHub API token for citus-bot
    - secure: "g4i26coVN7fWxEXm/5Y+8FrIsM02ZKk4iZGnZDtrjmbiiiYyZvyJcf8m6897nCI8FoDm6k4ifeozN3YfcktKKo4uJvWY09zf5R7KKIlmiU1bSRhiuGkL9QbnNthuPe1qLnn6QRMpALRM9qNkATHhH3MyGjThf7ZXeGGINbWx15W+RacFGsg83iqrNcSNRECoN/Tm6oQhi6tqC1ZUmOP8U5MlgN93HnU63Z8wN6Be0HGO9/MSpZPH/egMH5NNcxoWFLxRpdtlZWsxRGVHRdnDEFES2uI3nmFsCagJuxNTnQ77P2RVoxLkhIlgBW2KNNtRWes5ecECZY6v3nFDM4dzX9JiB2Jq1mAODVS36iTsRCPe8Gdkpxcb/df5TH+jt9XzIWywm+G+Ljzv52vXK8bq9pe1MA4y3Mt77gT+ml1p2MEpP4gNaVTPmzKa4x+9HcKvuSR/LBa+ExOwb/WveaFs3a11KX8m1BjOc0iZ02hlHcBlCCRvT0bE8WFdk8LvVP3fUkXQJezoPRRj5Bj02HSPFk/Vs7+PWzNE5Ml1e2CU8Qm/ok3Nut+hTTGwFo/sputFrNNHN7vKTlXaIsIbnq20HswRys/xTRuuN4cSR1bkVq1V1iFZ4KnAiKxaFHV62IsQwnoBxLm6pfnIjxzdXm4X2PQMc6fQIf9o9cRrclUY3gI="
    # PGXN password for citusdata
    - secure: "tA0sEJpfzC6r4CcGegFyt0B16pGdhveVsZqyEBhF6niKojgw7b/sZC8SA0eQXAgYfSpQs3t+WCsitNW9Wgbot/xkZQltKFTY//YZRMvHNGQenmiOQ03KpCHaR9QqtS1ZziYNY1W4H+qVxTHKCHISTCEj/oq+U3w/rSMvxBz8yGtVedGtBvZP8JfC2AepAqJAwMPfR71bYbAXNIJqywR5Hmd0zB+nAKNaXUY7FkyyZm89zXrkjMY467RsNlf9V1BbwpNtyAHNIwES97qEqTiMMmutW62K54FjibH8GmktzcmN0FQnXPaZoPzMf95RcYTgc1FPbZqgZodWf73HezpkrBsNiZ6DzACER5meLVV39ehw92iOW7noMN7qTsmtM7q64ERSILPdcTrN/xR0oc9JmdCTdeo1san7p0StEz88G1S3oPVNIEgVz6wxpxySWMnGlvEAsHDtFDPC0A4RiNixPKZIJsvHQU4r54vieJHJpqGuWGyKJtNZ4yitW89a4GZCX3b4XKuUR2swscrIxuKKolABwcZgFanZXp16av3z2qmKdV/o8cNDL2+pdpkqGErjbWvPo+JMh3Ia87FeYvbVRj8WjBGs7NCsC4p9NtulnEKHoUrcjsD961r4Oo73ZB5oYKF+k1ZV86+Qw8Tgl3M+TxQN/tOscIQ6WPSKN3AOR80="
before_install:
  - git clone -b v0.5.0 --depth 1 https://github.com/citusdata/tools.git
  - export PATH="$(pwd)/tools/travis:$PATH"
  - export PATH="$(pwd)/tools/packaging:$PATH"
install: true
script: release_pgxn
